#pragma once

/**
 * @file background.h
 * @brief Background image descriptor for the ST7789 display.
 *
 * The pixel data lives in background.c which is generated by the LVGL image
 * converter (https://lvgl.io/tools/imageconverter).
 *
 * To swap the background:
 *   1. Export your new image as 320x170 PNG
 *   2. Convert at lvgl.io/tools/imageconverter — Color format: RGB565, Output: C array
 *   3. Replace background.c with the new output.c, renaming the array and
 *      descriptor to background_map[] and background_img respectively
 *   4. Rebuild — no other files need to change
 */

#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

extern const lv_image_dsc_t background_img;
