#!/usr/bin/env python3
"""
make_background.py — Convert a PNG to an LVGL RGB565 C array for the ST7789 display.

Usage:
    python3 components/display/make_background.py <source.png> [brightness]

Arguments:
    source.png    Path to the source PNG image (any size — will be resized to 320x170)
    brightness    Optional brightness multiplier, 0.0–1.0 (default: 0.5)
                  The ST7789 backlight renders images significantly brighter than
                  a monitor — 0.5 is a good starting point, adjust to taste.

Output:
    components/display/background.c  (relative to project root)

Example:
    python3 components/display/make_background.py ~/Desktop/my_background.png 0.5
    python3 components/display/make_background.py ~/Desktop/my_background.png 0.6

Notes:
    - Output is always 320x170px, little-endian RGB565
    - Byte order confirmed via colour bar test on ST7789 + esp_lvgl_port with swap_bytes=true
    - Floyd-Steinberg dithering is applied to reduce banding on dark gradients
    - The display is 16-bit colour (5R/6G/5B) — subtle gradients will show banding;
      design backgrounds with bold contrast for best results
    - After running this script, rebuild the firmware: idf.py build && idf.py flash
"""

import sys
import os

try:
    from PIL import Image, ImageEnhance
except ImportError:
    print("Error: Pillow is not installed.")
    print("Install it with: pip3 install Pillow")
    sys.exit(1)

# ---- Constants ---------------------------------------------------------------

DISPLAY_W   = 320
DISPLAY_H   = 170
DEFAULT_BRIGHTNESS = 0.5

# Script lives in components/display/ — project root is two levels up
SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
OUTPUT_PATH = os.path.join(SCRIPT_DIR, 'background.c')

# ---- C file template ---------------------------------------------------------

HEADER = """\
#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMAGE_OUTPUT
#define LV_ATTRIBUTE_IMAGE_OUTPUT
#endif

/* Generated by components/display/make_background.py — do not edit by hand.
 * Source: {source}
 * Brightness: {brightness}
 * Size: {w}x{h} px, RGB565 little-endian
 */

"""

DESCRIPTOR = """\

const lv_image_dsc_t background_img = {{
  .header.cf = LV_COLOR_FORMAT_RGB565,
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.w = {w},
  .header.h = {h},
  .data_size = {pixels} * 2,
  .data = background_map,
}};
"""

# ---- Main --------------------------------------------------------------------

def convert(source_path, brightness):
    print(f"Source:     {source_path}")
    print(f"Brightness: {brightness}")
    print(f"Output:     {OUTPUT_PATH}")
    print()

    # Load and resize
    img = Image.open(source_path).convert('RGB').resize(
        (DISPLAY_W, DISPLAY_H), Image.LANCZOS
    )

    # Brightness adjustment
    img = ImageEnhance.Brightness(img).enhance(brightness)

    # Floyd-Steinberg dithering — reduces banding on dark gradients at RGB565 depth
    img = img.convert(
        'P', palette=Image.ADAPTIVE, dither=Image.FLOYDSTEINBERG, colors=256
    ).convert('RGB')

    # Convert to little-endian RGB565 byte array
    pixels = img.load()
    bytes_out = []
    for y in range(DISPLAY_H):
        for x in range(DISPLAY_W):
            r, g, b = pixels[x, y]
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            bytes_out.append(rgb565 & 0xFF)          # low byte first (little-endian)
            bytes_out.append((rgb565 >> 8) & 0xFF)

    # Format as C array — 16 pixels (32 bytes) per line
    lines = [
        '  ' + ', '.join(f'0x{b:02x}' for b in bytes_out[i:i+32]) + ','
        for i in range(0, len(bytes_out), 32)
    ]

    # Assemble file
    content = HEADER.format(
        source=os.path.basename(source_path),
        brightness=brightness,
        w=DISPLAY_W,
        h=DISPLAY_H,
    )
    content += (
        'const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST '
        'LV_ATTRIBUTE_IMAGE_OUTPUT uint8_t background_map[] = {\n'
    )
    content += '\n'.join(lines) + '\n};\n'
    content += DESCRIPTOR.format(w=DISPLAY_W, h=DISPLAY_H, pixels=DISPLAY_W * DISPLAY_H)

    with open(OUTPUT_PATH, 'w') as f:
        f.write(content)

    print(f"Written {len(bytes_out)} bytes ({DISPLAY_W}x{DISPLAY_H} px)")
    print()
    print("Next steps:")
    print("  idf.py build && idf.py flash monitor")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    source = os.path.expanduser(sys.argv[1])
    if not os.path.isfile(source):
        print(f"Error: file not found: {source}")
        sys.exit(1)

    brightness = DEFAULT_BRIGHTNESS
    if len(sys.argv) >= 3:
        try:
            brightness = float(sys.argv[2])
            if not 0.0 < brightness <= 1.0:
                raise ValueError
        except ValueError:
            print(f"Error: brightness must be a number between 0.0 and 1.0 (got '{sys.argv[2]}')")
            sys.exit(1)

    convert(source, brightness)


if __name__ == '__main__':
    main()
